// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVsnTCHlHarF84pvcyiuAaVmDEyw609Y',
    appId: '1:1087451936722:web:8052655db3fcbcea0dba0b',
    messagingSenderId: '1087451936722',
    projectId: 'proyectotfg-185c4',
    authDomain: 'proyectotfg-185c4.firebaseapp.com',
    storageBucket: 'proyectotfg-185c4.firebasestorage.app',
    measurementId: 'G-5R9W1FVK8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4q0ezDcb-j4qX5IEtg4_hGc_t6SzHlTM',
    appId: '1:1087451936722:android:76cd68e12093df030dba0b',
    messagingSenderId: '1087451936722',
    projectId: 'proyectotfg-185c4',
    storageBucket: 'proyectotfg-185c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFJTiobZMAnAyGAqKFap8DFz6h9vUvEA',
    appId: '1:1087451936722:ios:940002c4f441c8bf0dba0b',
    messagingSenderId: '1087451936722',
    projectId: 'proyectotfg-185c4',
    storageBucket: 'proyectotfg-185c4.firebasestorage.app',
    iosBundleId: 'com.example.frontTfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFJTiobZMAnAyGAqKFap8DFz6h9vUvEA',
    appId: '1:1087451936722:ios:940002c4f441c8bf0dba0b',
    messagingSenderId: '1087451936722',
    projectId: 'proyectotfg-185c4',
    storageBucket: 'proyectotfg-185c4.firebasestorage.app',
    iosBundleId: 'com.example.frontTfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTVsnTCHlHarF84pvcyiuAaVmDEyw609Y',
    appId: '1:1087451936722:web:34bf3df66d2dafd80dba0b',
    messagingSenderId: '1087451936722',
    projectId: 'proyectotfg-185c4',
    authDomain: 'proyectotfg-185c4.firebaseapp.com',
    storageBucket: 'proyectotfg-185c4.firebasestorage.app',
    measurementId: 'G-W02L3ZK596',
  );
}
